<meta http-equiv="Content-Type" content="text/html; ">
<meta name="viewport" content="width=device-width">
<title>{% title %}</title>

<script defer="defer" src='{% asset "apps/script/core.js" %}'></script>
<script defer="defer" src='{% asset "apps/script/widget.js" %}'></script>
<script defer="defer" src='{% asset "apps/script/module.js" %}'></script>
<script defer="defer" src='{% asset "apps/script/main.js" %}'></script>

<link rel="stylesheet" href='{% asset "apps/css/main.css" %}'>
{% section "css" %}{% endsection %}
{% section "javascript-body" %}{% endsection %}
